apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sadecekedi-ingress
  namespace: sadecekedi
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  rules:
    - host: api.sadecekedi.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-backend-service
                port:
                  number: 8080
    - host: minio.sadecekedi.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-service
                port:
                  number: 9001