services:
  localstack:
    image: localstack/localstack:4.4
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack_data:/var/lib/localstack

volumes:
  localstack_data:
